name: ar_quiz_app
description: A new Flutter AR quiz application.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  ar_flutter_plugin_2: ^0.0.3
  # qr_code_scanner:
  #   path: ./plugins/qr_code_scanner-1.0.1
  mobile_scanner: ^7.0.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.5.3

  # Other utilities
  image_gallery_saver_plus: ^4.0.1
  vector_math: ^2.1.4
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: PeaceSans
      fonts:
        - asset: assets/fonts/PeaceSans.ttf
